// <auto-generated />
using System;
using MarketEasyAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarketEasyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarketEasyAPI.Entities.Compras", b =>
                {
                    b.Property<Guid>("ComprasId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cantidad");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("ProductoId");

                    b.Property<Guid?>("ProductoId1");

                    b.Property<string>("UsuarioId");

                    b.Property<Guid?>("UsuarioId1");

                    b.HasKey("ComprasId");

                    b.HasIndex("ProductoId1");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("MarketEasyAPI.Entities.Producto", b =>
                {
                    b.Property<Guid>("ProductoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cantidad");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.Property<int>("Precio");

                    b.Property<string>("Tipo");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("MarketEasyAPI.Entities.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Contrasena");

                    b.Property<string>("Correo");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Nombres");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MarketEasyAPI.Entities.Compras", b =>
                {
                    b.HasOne("MarketEasyAPI.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId1");

                    b.HasOne("MarketEasyAPI.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1");
                });
#pragma warning restore 612, 618
        }
    }
}
